## ejercicio final 
## Paso 4 - Usar el runner en el workflow

name: CI (dummy)
env:
    IMAGE_NAME: a
    APP_URL: b

on: ## Event triggers (on:): cuándo se ejecuta (push, PR, manual, schedule, etc.).
  push: ## El workflow se ejecutará cada vez que alguien suba código (haga un git push) a cualquier rama del repositorio
  pull_request:
    branches: [develop, master] ##El workflow solo se activará si se abre (o se actualiza) un Pull Request que tenga como objetivo las ramas develop o master.
  workflow_dispatch: ##Clic manual en la web
    inputs:
      RUN_CD:
        description: "Run CD stage"
        required: false
        type: boolean
        default: false
      DEPLOY_ENV:
        description: "Entorno de despliegue"
        required: false
        type: choice
        options:
          - DEV
          - PRO
        default: DEV

jobs: ## contenedor de todas las tareas. Aquí puedes tener varios (ej: ci, test, deploy).
  ci: ## Es el identificador de este job.
    name: Integración Continua
    #runs-on: ubuntu-latest # Define el sistema operativo (Linux) 
    #runs-on: self-hosted # para ejecutarlo con la herramienta de git en local
    runs-on: [self-hosted, linux, docker]
    env:
      IMAGE_NAME: c
      APP_URL: d
    environment: DEV ## o seleccionar de manera dinamica DEV vs PRO:  ${{ github.ref_name == 'master' && 'PRO' || 'DEV' }}
    steps: ## Es la lista secuencial de tareas.
      - name: Checkout del repositorio
        uses: actions/checkout@v4 # Copia tu código en el runner. esta línea "descarga" tu código dentro de la máquina para que puedas trabajar con él (leer archivos, compilar, etc.).
      - name: Info
        run: |
          echo "refname: ${{ github.ref_name }}"
          echo "sha: ${{ github.sha }}"
          echo "os: ${{ runner.os }}"
          echo "name: ${{ runner.name }}"      
      - name: "Mostrar valores"
        run: |
          echo "IMAGE_NAME: ${{ env.IMAGE_NAME }}"
          echo "APP_URL: ${{ env.APP_URL }}"
      - name: "Mostrar Parámetros inputs"
        run: |
          echo "RUN_CD: ${{ inputs.RUN_CD }}"
      - name: "Mostrar environment DEV"
        run: |
          echo "REGISTRY_HOST: ${{ vars.REGISTRY_HOST }}"
          echo "ARTIFACTORY_URL: ${{ vars.ARTIFACTORY_URL  }}"
          echo "REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}"
      - name: "Construir imagen y ejecutar Tests/Lint" ## Al usar el flag -f, le indicas a Docker la ruta exacta y el nombre de tu archivo. Si no lo pones, Docker buscará por defecto un archivo llamado simplemente Dockerfile en la raíz, y fallará.
        run: |
          docker build -t mi-aplicacion-ci:0.0.1 \
            -f devops/ci.Dockerfile .
  cd:
    name: Despliegue Continuo
    needs: ci # Asegura que el CI pase primero
    if: github.ref_name == 'develop' || github.ref_name == 'master' || github.ref_name == 'main' || inputs.RUN_CD == true
    #runs-on: ubuntu-latest    
    #runs-on: self-hosted
    runs-on: [self-hosted, linux, docker]
    steps: 
      - name: "Validación de Condición de Despliegue"
        run: |
          echo "rama: ${{ github.ref_name }}"
          echo "inputs.RUN_CD: ${{ inputs.RUN_CD }}"    
      - name: "Checkout del repositorio"
        uses: actions/checkout@v4    
      - name: "Volver a construir la imagen en este job." ## Otra opcion es subirla al Registry
        run:  docker build -t mi-aplicacion-ci:0.0.1 -f devops/ci.Dockerfile . ## # Necesitamos construirla AQUÍ para que el Compose la encuentre
      - name: "Verificar Directorio y Archivos"
        run: |
          echo "📍 Directorio actual: $(pwd)"
          echo "📂 Contenido del directorio:"
          ls -R
          
          if [ -f "docker-compose.yml" ]; then
            echo "✅ docker-compose.yml encontrado en la raíz."
          else
            echo "❌ ERROR: No veo el archivo docker-compose.yml"
            exit 1
          fi        
      - name: "Levantar contenedor"
        run: docker compose up -d  
      - name: "Esperar 10 segundos a que se carguen los servicios"
        run: sleep 10
      - name: "Inspeccionar recursos creados"
        run: |
          echo "--- CONTENEDORES ACTIVOS ---"
          docker ps -a 
          echo -e "\n--- REDES DE DOCKER ---"
          docker network ls
          echo -e "\n--- VOLÚMENES ---"
          docker volume ls  
      - name: "Cleanup"
        if: always() ## siempre se ejecuta
        run: |
          echo "Limpiando contenedores y volúmenes..."
          docker compose down -v
