## ejercicio 2

name: CI (dummy)

on: ## Event triggers (on:): cuándo se ejecuta (push, PR, manual, schedule, etc.).
  push: ## El workflow se ejecutará cada vez que alguien suba código (haga un git push) a cualquier rama del repositorio
  pull_request:
    branches: [develop, master] ##El workflow solo se activará si se abre (o se actualiza) un Pull Request que tenga como objetivo las ramas develop o master.
  workflow_dispatch: ##Clic manual en la web
    inputs:
      RUN_CD:
        description: "Run CD stage"
        required: false
        type: boolean
        default: false

jobs: ## contenedor de todas las tareas. Aquí puedes tener varios (ej: ci, test, deploy).
  ci: ## Es el identificador de este job.
    name: Integración Continua
    runs-on: ubuntu-latest # Define el sistema operativo (Linux)

    steps: ## Es la lista secuencial de tareas.
      - name: Checkout del repositorio
        uses: actions/checkout@v4 # Copia tu código en el runner. esta línea "descarga" tu código dentro de la máquina para que puedas trabajar con él (leer archivos, compilar, etc.).
      - name: Info
        run: echo ${{github.ref_name}} ${{github.sha}} ${{runner.os}} ${{runner.name}}
         
